version: '3.8'
services:
  api-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    image: ${API_NAME}
    container_name: ${API_NAME}
    build:
      context: .
      dockerfile: dockerfile
      target: base
      args:
        NODE_ENV: development
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    depends_on:
      - api-db
    expose:
      - ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    command: yarn run dev
volumes:
  db:
    driver: local
