version: '3.8'
services:
  api-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: opticourse-api
    build: .
    image: opticourse-api
    depends_on:
      - api-db
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - './:/src'
volumes:
  db:
    driver: local
